title: Jesus Dominguez - OS page 
author: JAnDo IT GitHub User
email: jandoz.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Connecting Big Data, ML, AI and Programming!
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# social links
jando2k: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
JAnDo-IT:  your-github-handle # DO NOT include the @ character, or else the build will fail!

#Theme and Setups
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
